// Replace with your keys.
window.TRUTHLENS_CONFIG = {
  FACTCHECK_API_KEY: "REPLACE_WITH_GOOGLE_FACTCHECK_KEY",
  NEWS_API_KEY: "REPLACE_WITH_NEWSAPI_KEY",
  NEWSDATA_API_KEY: "REPLACE_WITH_NEWSDATA_KEY",
  GNEWS_API_KEY: "REPLACE_WITH_GNEWS_KEY",
  LINKPREVIEW_API_KEY: "REPLACE_WITH_LINKPREVIEW_KEY",
};
